modified:   .gitignore 	modified:   tfFiles/CreateBasionHost.tf 	modified:   tfFiles/Variables.tf 	new file:   tfFiles/dynamicFiles/aws_hosts 	modified:   tfFiles/templateFiles/BasionHost.tpl 	modified:   tfFiles/unixScripts/loopTillport22ComeUp
	modified:   .gitignore
	modified:   tfFiles/CreateBasionHost.tf
	modified:   tfFiles/Variables.tf
	new file:   tfFiles/dynamicFiles/aws_hosts
	modified:   tfFiles/templateFiles/BasionHost.tpl
	modified:   tfFiles/unixScripts/loopTillport22ComeUp

diff --git a/tfFiles/unixScripts/loopTillport22ComeUp b/tfFiles/unixScripts/loopTillport22ComeUp
--- a/tfFiles/unixScripts/loopTillport22ComeUp
+++ b/tfFiles/unixScripts/loopTillport22ComeUp
@@ -1,4 +1,16 @@
 #!/bin/bash
+###############################################################################################################
+#
+#
+#
+################################################################################################################
+if [ $# -ne 1 ]
+then
+echo "Error - incorrect number of arguments passed"
+echo "USAGGE - loopTillport22ComeUp IPADDRESS"
+exit 1
+fi
+ 
 test=1
 while [ $test -ne 0 ]
 do
